"""initial schema

Revision ID: 08c4b4b29bf4
Revises: 
Create Date: 2026-04-15 16:47:51.538533
"""
from __future__ import annotations

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '08c4b4b29bf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dismissed_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_address', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Enum('not_residential', 'outside_market', 'duplicate', 'too_small', 'other', name='dismiss_reason_enum'), nullable=False),
    sa.Column('dismissed_by', sa.String(length=50), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dismissed_records')),
    sa.UniqueConstraint('source', 'source_record_id', name=op.f('uq_dismissed_records_source'))
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_address', sa.String(length=255), nullable=False),
    sa.Column('raw_addresses', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('geocode_confidence', sa.Enum('high', 'medium', 'low', 'none', name='geocode_confidence_enum'), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=False),
    sa.Column('zip', sa.String(length=10), nullable=True),
    sa.Column('tcg_region', sa.String(length=150), nullable=True),
    sa.Column('jurisdiction', sa.String(length=150), nullable=True),
    sa.Column('costar_submarket', sa.String(length=150), nullable=True),
    sa.Column('zoning', sa.String(length=120), nullable=True),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('previous_names', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('developer', sa.String(length=255), nullable=True),
    sa.Column('applicant', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rent_or_sale', sa.Enum('Rental', 'For-Sale', 'Both', 'Unknown', name='rent_or_sale_enum'), nullable=False),
    sa.Column('product_type', sa.Enum('Apartment', 'Condo', 'Single-Family', 'Townhome', 'Micro/Co-Living', 'Other', 'Unknown', name='product_type_enum'), nullable=False),
    sa.Column('age_restriction', sa.Enum('Non Age-Restricted', 'Senior', 'Student', 'Unknown', name='age_restriction_enum'), nullable=False),
    sa.Column('stories', sa.Integer(), nullable=True),
    sa.Column('total_units', sa.Integer(), nullable=True),
    sa.Column('market_rate_units', sa.Integer(), nullable=True),
    sa.Column('affordable_units', sa.Integer(), nullable=True),
    sa.Column('pct_studio', sa.Float(), nullable=True),
    sa.Column('pct_1bed', sa.Float(), nullable=True),
    sa.Column('pct_2bed', sa.Float(), nullable=True),
    sa.Column('pct_other_bed', sa.Float(), nullable=True),
    sa.Column('acres', sa.Float(), nullable=True),
    sa.Column('retail_sf', sa.Integer(), nullable=True),
    sa.Column('office_sf', sa.Integer(), nullable=True),
    sa.Column('hotel_keys', sa.Integer(), nullable=True),
    sa.Column('total_sf', sa.Integer(), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=100), nullable=True),
    sa.Column('affordable_type', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('true_owner', sa.String(length=255), nullable=True),
    sa.Column('architect', sa.String(length=255), nullable=True),
    sa.Column('pipeline_status', sa.Enum('Conceptual', 'Proposed', 'Pending', 'Approved', 'Under Construction', 'Pre-Leasing/Pre-Selling', 'Complete', 'Stalled', 'Inactive', 'Delete-Duplicate', 'Delete-Outside Market Area', 'Delete-Not Residential', name='pipeline_status_enum'), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('status_confidence', sa.Enum('high', 'medium', 'low', name='status_confidence_enum'), nullable=False),
    sa.Column('status_source', sa.String(length=120), nullable=True),
    sa.Column('date_delivery', sa.Date(), nullable=True),
    sa.Column('date_construction_start', sa.Date(), nullable=True),
    sa.Column('entitlement_type', sa.String(length=120), nullable=True),
    sa.Column('appeal_status', sa.String(length=120), nullable=True),
    sa.Column('ceqa_status', sa.String(length=120), nullable=True),
    sa.Column('planner_1_name', sa.String(length=255), nullable=True),
    sa.Column('planner_1_city', sa.String(length=120), nullable=True),
    sa.Column('planner_1_email', sa.String(length=255), nullable=True),
    sa.Column('planner_1_phone', sa.String(length=50), nullable=True),
    sa.Column('planner_2_name', sa.String(length=255), nullable=True),
    sa.Column('planner_2_city', sa.String(length=120), nullable=True),
    sa.Column('planner_2_email', sa.String(length=255), nullable=True),
    sa.Column('planner_2_phone', sa.String(length=50), nullable=True),
    sa.Column('researcher_notes', sa.Text(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('source_urls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('last_editor', sa.String(length=50), nullable=True),
    sa.Column('last_edit_date', sa.Date(), nullable=True),
    sa.Column('last_reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('last_reviewed_date', sa.Date(), nullable=True),
    sa.Column('researcher_override', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('ix_projects_canonical_address', 'projects', ['canonical_address'], unique=False)
    op.create_index('ix_projects_market', 'projects', ['market'], unique=False)
    op.create_index('ix_projects_pipeline_status', 'projects', ['pipeline_status'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=100), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('run_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('records_pulled', sa.Integer(), nullable=False),
    sa.Column('new_matches', sa.Integer(), nullable=False),
    sa.Column('updates_found', sa.Integer(), nullable=False),
    sa.Column('new_candidates', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_index('ix_source_runs_market_source_name', 'source_runs', ['market', 'source_name'], unique=False)
    op.create_table('project_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.Enum('apn', 'zimas_pin', 'case_number', 'permit_number', 'costar_property_id', 'tcg_pipedream_id', name='identifier_type_enum'), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_identifiers_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_identifiers')),
    sa.UniqueConstraint('identifier_type', 'value', name=op.f('uq_project_identifiers_identifier_type'))
    )
    op.create_index('ix_project_identifiers_project_id', 'project_identifiers', ['project_id'], unique=False)
    op.create_table('project_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('related_project_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('phase', 'master_plan', 'counterpart', 'duplicate', 'supersedes', name='relationship_type_enum'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_relationships_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_project_id'], ['projects.id'], name=op.f('fk_project_relationships_related_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_relationships')),
    sa.UniqueConstraint('project_id', 'related_project_id', 'relationship_type', name=op.f('uq_project_relationships_project_id'))
    )
    op.create_table('project_source_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pulled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mapped_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('field_provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_source_records_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_source_records')),
    sa.UniqueConstraint('source_name', 'source_record_id', name=op.f('uq_project_source_records_source_name'))
    )
    op.create_table('review_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('source_run_id', sa.UUID(), nullable=True),
    sa.Column('item_type', sa.Enum('new_candidate', 'status_change', 'possible_match', 'potential_stall', 'low_confidence', name='review_item_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('open', 'accepted', 'rejected', 'deferred', 'auto_accepted', name='review_item_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority_enum'), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_to', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_review_items_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_run_id'], ['source_runs.id'], name=op.f('fk_review_items_source_run_id_source_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_items'))
    )
    op.create_index('ix_review_items_status_priority', 'review_items', ['status', 'priority'], unique=False)
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('Conceptual', 'Proposed', 'Pending', 'Approved', 'Under Construction', 'Pre-Leasing/Pre-Selling', 'Complete', 'Stalled', 'Inactive', 'Delete-Duplicate', 'Delete-Outside Market Area', 'Delete-Not Residential', name='pipeline_status_enum'), nullable=False),
    sa.Column('status_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_status_history_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_history'))
    )
    op.create_table('change_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('review_item_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('field', sa.String(length=120), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('change_type', sa.Enum('auto_accepted', 'researcher_confirmed', 'researcher_rejected', 'researcher_override', name='change_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'low', name='priority_enum'), nullable=False),
    sa.Column('reviewed_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_change_log_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], name=op.f('fk_change_log_review_item_id_review_items'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_log'))
    )
    op.create_table('review_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('review_item_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('accept', 'reject', 'override', 'defer', 'note', name='review_decision_action_enum'), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('field_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_item_id'], ['review_items.id'], name=op.f('fk_review_decisions_review_item_id_review_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_decisions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_decisions')
    op.drop_table('change_log')
    op.drop_table('status_history')
    op.drop_index('ix_review_items_status_priority', table_name='review_items')
    op.drop_table('review_items')
    op.drop_table('project_source_records')
    op.drop_table('project_relationships')
    op.drop_index('ix_project_identifiers_project_id', table_name='project_identifiers')
    op.drop_table('project_identifiers')
    op.drop_index('ix_source_runs_market_source_name', table_name='source_runs')
    op.drop_table('source_runs')
    op.drop_index('ix_projects_pipeline_status', table_name='projects')
    op.drop_index('ix_projects_market', table_name='projects')
    op.drop_index('ix_projects_canonical_address', table_name='projects')
    op.drop_table('projects')
    op.drop_table('dismissed_records')
    op.execute("DROP TYPE IF EXISTS review_decision_action_enum")
    op.execute("DROP TYPE IF EXISTS change_type_enum")
    op.execute("DROP TYPE IF EXISTS review_item_type_enum")
    op.execute("DROP TYPE IF EXISTS review_item_status_enum")
    op.execute("DROP TYPE IF EXISTS relationship_type_enum")
    op.execute("DROP TYPE IF EXISTS identifier_type_enum")
    op.execute("DROP TYPE IF EXISTS dismiss_reason_enum")
    op.execute("DROP TYPE IF EXISTS geocode_confidence_enum")
    op.execute("DROP TYPE IF EXISTS status_confidence_enum")
    op.execute("DROP TYPE IF EXISTS age_restriction_enum")
    op.execute("DROP TYPE IF EXISTS product_type_enum")
    op.execute("DROP TYPE IF EXISTS rent_or_sale_enum")
    op.execute("DROP TYPE IF EXISTS priority_enum")
    op.execute("DROP TYPE IF EXISTS pipeline_status_enum")
    # ### end Alembic commands ###
