"""add lookup indexes

Revision ID: 8ee2234b3cce
Revises: 08c4b4b29bf4
Create Date: 2026-04-15 17:13:20.652604
"""
from __future__ import annotations

from alembic import op


# revision identifiers, used by Alembic.
revision = '8ee2234b3cce'
down_revision = '08c4b4b29bf4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_change_log_project_id_timestamp', 'change_log', ['project_id', 'timestamp'], unique=False)
    op.create_index('ix_project_identifiers_value', 'project_identifiers', ['value'], unique=False)
    op.create_index('ix_project_relationships_related_project_id', 'project_relationships', ['related_project_id'], unique=False)
    op.create_index('ix_project_source_records_project_id', 'project_source_records', ['project_id'], unique=False)
    op.create_index('ix_status_history_project_id_status_date', 'status_history', ['project_id', 'status_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_status_history_project_id_status_date', table_name='status_history')
    op.drop_index('ix_project_source_records_project_id', table_name='project_source_records')
    op.drop_index('ix_project_relationships_related_project_id', table_name='project_relationships')
    op.drop_index('ix_project_identifiers_value', table_name='project_identifiers')
    op.drop_index('ix_change_log_project_id_timestamp', table_name='change_log')
    # ### end Alembic commands ###
